apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9002"
    spec:
      containers:
        - name: order-service
          image: order-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://restaurant-postgres/restaurantdb_order
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name : SPRING_R2DBC_URL
              value: r2dbc:postgresql://restaurant-postgres:5432/restaurantdb_order
            - name: RESTAURANT_TASTY_SERVICE_URI
              value: http://tasty-service
            - name: SPRING_RABBITMQ_  HOST
              value: restaurant-rabbitmq
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://restaurant-keycloak/realms/restaurant
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9002
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9002
            initialDelaySeconds: 5
            periodSeconds: 15
          volumeMounts:
            - name: order-config-volume
              mountPath: /workspace/config
      volumes:
        - name: order-config-volume
          configMap:
            name: order-config
